repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: c48217e1fc006c2dddd14df54e83b67da15de5cd  # frozen: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/rstcheck/rstcheck
    rev: d8774e96810795967ed9603f445b4e751e7b313f  # frozen: v6.3.0
    hooks:
      - id: rstcheck
